# C++ Console Executable Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`

ifndef CONFIG
  CONFIG=Debug
endif

ifeq ($(CONFIG),Debug)
  BINDIR = ./bin
  LIBDIR = .
  OBJDIR = obj/Debug
  OUTDIR = ./bin
  CPPFLAGS = -MD
  CFLAGS += $(CPPFLAGS) -g `wx-config --cxxflags`
  CXXFLAGS = $(CFLAGS)
  LDFLAGS += -L$(BINDIR) -L$(LIBDIR) `wx-config --libs`
  LDDEPS =
  TARGET = xmule
endif

ifeq ($(CONFIG),Release)
  BINDIR = ./bin
  LIBDIR = .
  OBJDIR = obj/Release
  OUTDIR = ./bin
  CPPFLAGS = -MD
  CFLAGS += $(CPPFLAGS) -O2 `wx-config --cxxflags`
  CXXFLAGS = $(CFLAGS)
  LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -s `wx-config --libs`
  LDDEPS =
  TARGET = xmule
endif

OBJECTS = \
	$(OBJDIR)/xApp.o \
	$(OBJDIR)/xKadPanel.o \
	$(OBJDIR)/xMainFrame.o \
	$(OBJDIR)/xSearchPanel.o \
	$(OBJDIR)/xServersPanel.o \
	$(OBJDIR)/xSharedFilesPanel.o \
	$(OBJDIR)/xTransfersPanel.o \
	$(OBJDIR)/xOptionsDialog.o \
	$(OBJDIR)/xSafeFile.o \
	$(OBJDIR)/xServer.o \
	$(OBJDIR)/xTag.o \

.PHONY: clean

$(OUTDIR)/$(TARGET): $(OBJECTS) $(LDDEPS)
	@echo Linking xMule
	-@if [ ! -d $(BINDIR) ]; then mkdir -p $(BINDIR); fi
	-@if [ ! -d $(LIBDIR) ]; then mkdir -p $(LIBDIR); fi
	@$(CXX) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	@echo Cleaning xMule
	-@rm -rf $(OUTDIR)/$(TARGET) $(OBJDIR)/*

$(OBJDIR)/xApp.o: xApp.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xKadPanel.o: xMainFrame/xKadPanel.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xMainFrame.o: xMainFrame/xMainFrame.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xSearchPanel.o: xMainFrame/xSearchPanel.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xServersPanel.o: xMainFrame/xServersPanel.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xSharedFilesPanel.o: xMainFrame/xSharedFilesPanel.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xTransfersPanel.o: xMainFrame/xTransfersPanel.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xOptionsDialog.o: xMainFrame/xOptions/xOptionsDialog.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xSafeFile.o: xCore/xSafeFile.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xServer.o: xCore/xServer.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/xTag.o: xCore/xTag.cpp
	-@if [ ! -d $(OBJDIR) ]; then mkdir -p $(OBJDIR); fi
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

-include $(OBJECTS:%.o=%.d)

